### ISSUE TITLE
Some apps don't like the name

### ISSUE THREAD

**Issue by ktekinay** [0xType/0xProto#15] opened 2023-09-13 17:59 UTC
0xProto and it might become my favorite dev font but I can't seem to use it everywhere. Some apps on the Mac are recognizing the font but not loading it presumably because the name starts with a number.

For example, when I try to use it as my mono font in Mail, it displays a generic proportional font instead. When I tried to set it as my default in VS Studio Code, I had to enclose it in single quotes or it would do the same.

Can you release a duplicate version with a name like "ZeroExProto" to avoid these issues?

**Comment by masaakim** [comment] 2023-09-14 01:46
@ktekinay Thank you for using 0xProto!

I've also noticed that when I type using 0xProto in Mail.app on macOS, it displays in a proportional font instead.

However, I'll look into whether the issue is because the name starts with "0xProto". Given that 0xProto appears in Mail.app's font list, I suspect the name might not be the problem but rather some other underlying cause.

A font file can't simply be renamed to an alternative like "ZeroExProto" for 0xProto; it would need to be provided as a separate font file. I'd prefer not to take that route due to the associated administrative costs.

If this issue arises from names beginning with a number, then I may consider renaming 0xProto.

**Comment by anilkumar150886** [comment] 2023-09-20 07:11
Just an Observation : The new version of 1.2 has this issue on the cmd as well.. when I select the font, it goes to default font type.. The issue is not present in 1.01 version and is fine.. So, I reverted back to 1.01 version as of now..

**Comment by masaakim** [comment] 2023-09-20 08:01
@anilkumar150886 Thanks for the feedback. 
Are you saying that 0xProto no longer lists in the cmd? Is this the same status as your feedback on https://github.com/0xType/0xProto/issues/10 at this time?

> So, I reverted back to 1.01 version as of now..

You mean, you reverted back to [v1.101](https://github.com/0xType/0xProto/releases/tag/1.101) instead of v1.01, right?

**Comment by anilkumar150886** [comment] 2023-09-20 09:38
This time, on v1.2 version, the font was listing in the cmd, but it was not getting recognized as font. i.e, Whenever i selected the 0xProto, it was defaulted back to courier new.

So, i reverted back to v1.101.. (sorry for the confusion on the font version).

With v1.101, it's fine, i.e, when i select the 0xProto, the font is recognized.

**Comment by masaakim** [comment] 2023-09-20 11:06
@anilkumar150886 Thanks!
Your feedback seems to be unrelated to the font name.  I've created a new issue for it, #21 .

**Comment by masaakim** [comment] 2023-10-01 02:06
Per the [OpenType specification](https://learn.microsoft.com/en-us/typography/opentype/spec/name), there aren't any restrictions on font names, so '0xProto' is perfectly valid. However, in applications like VS Code, where you enter the font name into a text field, it requires the name to be enclosed in quotation marks. This isn't typical for other fonts. Given that the font name '0xProto' starts with a number, it isn't the most user-friendly experience.
As a result, I'm considering renaming the font, if necessary. (I like the name '0xProto', though of course I don't want to rename it.)

**Comment by masaakim** [comment] 2023-10-01 02:15
Also, 

> when I try to use it as my mono font in Mail, it displays a generic proportional font instead.

I locally renamed 0xProto to zxProto (a name not beginning with a number) and tested this with my build.
The result was consistent: Even with the name changed to zxProto, the font wasn't available on Mail.app. Hence, I've determined that the issue isn't tied to the name '0xProto'.

**Comment by masaakim** [comment] 2023-10-01 02:35
I've created https://github.com/0xType/0xProto/issues/26 and https://github.com/0xType/0xProto/issues/27 since this issue can be split into two distinct concerns. Therefore, I'll be closing this issue.

**Closed by masaakim** 2023-10-01 02:35 UTC
